[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/bbox"
  to = "/.netlify/functions/bbox"
  status = 200
  force = true
  query = ":query"
