import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ImplemtedMap from "@/components/implemented-map";
import Header from "@/components/header/header";
import WindowWithDynamicRounding from "@/components/elements/window-with-dynamic-rounding";
import { LayoutSettingsProvider } from "@/contexts/layout-settings-context";
import LayoutSettingOverride from "@/components/elements/layout-setting-override";
import { ThemeProvider } from "@/providers/theme-provider";
import { Analytics } from "@vercel/analytics/react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen`}
      >
        <Analytics />

        <div className="absolute top-0 left-0 w-full h-full z-0">
          <ImplemtedMap />
        </div>

        <div className="absolute z-10 flex h-screen p-6">
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <LayoutSettingsProvider>
              <LayoutSettingOverride key="RootLayout" rounded={true} />

              <WindowWithDynamicRounding dynamicRoundingClassName="rounded-r-none">
                <Header />
              </WindowWithDynamicRounding>
              {children}
            </LayoutSettingsProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
