FROM ghcr.io/maplibre/martin:main

# Set the environment variables
ENV PGPASSWORD=postgres

# Copy the configuration file into the container
COPY config.yaml /config/config.yaml

# Define the command to run Martin with the configuration file
CMD ["--config", "/config/config.yaml"]