FROM node:22 AS builder
WORKDIR /app

COPY poi-index/package*.json ./

RUN npm ci

COPY poi-index ./

RUN npm run build

FROM node:22-slim AS runner
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY poi-index/package*.json ./
COPY poi-index/tsconfig.json ./
COPY poi-index/.env* ./

RUN npm ci --only=production

EXPOSE 3001

CMD ["npm", "run", "start:prod"]