services:
  db:
    image: db:v1
    shm_size: 16g
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PG_MAX_WAL_SIZE=4GB
      - PG_CHECKPOINT_TIMEOUT=30min
      - PG_WORK_MEM=256MB
      - PG_MAINTENANCE_WORK_MEM=4GB
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nominatim:
    image: mediagis/nominatim:5.1
    environment:
      # - PBF_URL=https://download.openstreetmap.fr/extracts/europe/netherlands.osm.pbf
      # - PBF_URL=https://download.openstreetmap.fr/extracts/europe/netherlands/flevoland-latest.osm.pbf
      - PBF_URL=https://download.openstreetmap.fr/extracts/europe/netherlands/gelderland-latest.osm.pbf
    ports:
      - "8088:8080"

  replication:
    image: replication:v1
    build:
      context: .
      dockerfile: Dockerfile.replication
    volumes:
      - .:/app
    depends_on:
      import:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - REPLICATION_INTERVAL=60
      - PG_MAX_WAL_SIZE=4GB
      - PG_CHECKPOINT_TIMEOUT=30min
      - PG_WORK_MEM=256MB
      - PG_MAINTENANCE_WORK_MEM=4GB
      - OSM2PGSQL_CACHE=40000
      - OSM2PGSQL_NUMPROC=16

  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_MAX_WAL_SIZE=4GB
      - PG_CHECKPOINT_TIMEOUT=30min
      - PG_WORK_MEM=256MB
      - PG_MAINTENANCE_WORK_MEM=4GB
      - OSM2PGSQL_CACHE=40000
      - OSM2PGSQL_NUMPROC=16
      # - OSM2PGSQL_DATAFILE=https://download.openstreetmap.fr/extracts/europe/netherlands.osm.pbf
      # - OSM2PGSQL_DATAFILE=https://download.openstreetmap.fr/extracts/europe/netherlands/flevoland-latest.osm.pbf
      - OSM2PGSQL_DATAFILE=https://download.openstreetmap.fr/extracts/europe/netherlands/gelderland-latest.osm.pbf
      - EXTERNAL_DATA_SCRIPT_FLAGS

  martin:
    image: martin:v1
    build:
      context: .
      dockerfile: Dockerfile.martin
    volumes:
      - .:/app
    ports:
      - "3456:3000"
    depends_on:
      import:
        condition: service_completed_successfully
      setup:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC

  setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    environment:
      - PORT=3001
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=gis
      - NODE_ENV=production
      - NOMINATIM_URL=http://nominatim:8088
    depends_on:
      import:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=3001
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=gis
      - NODE_ENV=production
      - NOMINATIM_URL=http://nominatim:8080
    depends_on:
      import:
        condition: service_completed_successfully
      setup:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      martin:
        condition: service_healthy
    ports:
      - "3001:3001"

  geocode:
    build:
      context: .
      dockerfile: Dockerfile.geocode
    environment:
      - PORT=3001
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=gis
      - NODE_ENV=production
      - NOMINATIM_URL=http://nominatim:8088
    depends_on:
      setup:
        condition: service_completed_successfully
      import:
        condition: service_completed_successfully
      db:
        condition: service_healthy
