services:
  db:
    image: db:v1
    shm_size: 16g
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PG_MAX_WAL_SIZE=4GB
      - PG_CHECKPOINT_TIMEOUT=30min
      - PG_WORK_MEM=256MB
      - PG_MAINTENANCE_WORK_MEM=4GB
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  replication:
    image: replication:v1
    build:
      context: .
      dockerfile: Dockerfile.replication
    volumes:
      - .:/app
    depends_on:
      import:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - REPLICATION_INTERVAL=60
      - PG_MAX_WAL_SIZE=4GB
      - PG_CHECKPOINT_TIMEOUT=30min
      - PG_WORK_MEM=256MB
      - PG_MAINTENANCE_WORK_MEM=4GB
      - OSM2PGSQL_CACHE=40000
      - OSM2PGSQL_NUMPROC=16

  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
    restart: "no"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_MAX_WAL_SIZE=4GB
      - PG_CHECKPOINT_TIMEOUT=30min
      - PG_WORK_MEM=256MB
      - PG_MAINTENANCE_WORK_MEM=4GB
      - OSM2PGSQL_CACHE=40000
      - OSM2PGSQL_NUMPROC=16
      # - OSM2PGSQL_DATAFILE=https://download.openstreetmap.fr/extracts/europe/netherlands.osm.pbf
      - OSM2PGSQL_DATAFILE=https://download.openstreetmap.fr/extracts/europe/netherlands/gelderland-latest.osm.pbf
      - EXTERNAL_DATA_SCRIPT_FLAGS
